namespace: stnvivanco92-dev

app:
  name: database
  role: database
  image: savivancofi/database
  tag: v1              # primera versi√≥n de tu imagen de DB
  replicas: 1
  containerPort: 5432
  servicePort: 5432
  createRoute: false   # la base de datos no se expone hacia afuera del cluster

env:
  - name: POSTGRES_DB
    value: "retodb"
  - name: POSTGRES_USER
    value: "reto_user"
  - name: POSTGRES_PASSWORD
    value: "reto_pass"

pvc:
  enabled: false
  storageClassName: ""
  storageSize: ""
  mountPath: ""