namespace: stnvivanco92-dev

app:
  name: database
  role: database
  image: savivancofi/database
  tag: v3
  replicas: 1
  containerPort: 5432
  servicePort: 5432
  createRoute: false

env:
  - name: POSTGRES_DB
    value: "retodb"
  - name: POSTGRES_USER
    value: "reto_user"
  - name: POSTGRES_PASSWORD
    value: "reto_pass"
  - name: PGDATA
    value: "/tmp/pgdata"

pvc:
  enabled: false
